<?php

/**
 * This is the model base class for the table "tb_entidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbEntidade".
 *
 * Columns in table "tb_entidade" available as properties of the model,
 * followed by relations of table "tb_entidade" available as properties of the model.
 *
 * @property integer $id_entidade
 * @property string $nome
 *
 * @property TbAgendaMov[] $tbAgendaMovs
 * @property TbMovimentos[] $tbMovimentoses
 */
abstract class BaseTbEntidade extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tb_entidade';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Entidade|Entidades', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>255),
			array('nome', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_entidade, nome', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tbAgendaMovs' => array(self::HAS_MANY, 'TbAgendaMov', 'entidade'),
			'tbMovimentoses' => array(self::HAS_MANY, 'TbMovimentos', 'entidade'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_entidade' => Yii::t('app', 'Id Entidade'),
			'nome' => Yii::t('app', 'Nome'),
			'tbAgendaMovs' => null,
			'tbMovimentoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_entidade', $this->id_entidade);
		$criteria->compare('nome', $this->nome, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}