<?php

/**
 * This is the model base class for the table "tb_carros".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbCarros".
 *
 * Columns in table "tb_carros" available as properties of the model,
 * followed by relations of table "tb_carros" available as properties of the model.
 *
 * @property integer $id_carro
 * @property string $matricula
 * @property string $marca
 * @property string $modelo
 * @property integer $km_iniciais
 * @property string $data_matricula
 * @property integer $seguro
 * @property integer $combust_inicial
 *
 * @property TbSeguros $seguro0
 * @property TbDespesasCarros[] $tbDespesasCarroses
 * @property TbSeguros[] $tbSeguroses
 */
abstract class BaseTbCarros extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tb_carros';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Carro|Carros', $n);
	}

	public static function representingColumn() {
		return 'matricula';
	}

	public function rules() {
		return array(
			array('km_iniciais, seguro, combust_inicial', 'numerical', 'integerOnly'=>true),
			array('matricula, marca, modelo', 'length', 'max'=>45),
			array('data_matricula', 'safe'),
			array('matricula, marca, modelo, km_iniciais, data_matricula, seguro, combust_inicial', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_carro, matricula, marca, modelo, km_iniciais, data_matricula, seguro, combust_inicial', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'seguro0' => array(self::BELONGS_TO, 'TbSeguros', 'seguro'),
			'tbDespesasCarroses' => array(self::HAS_MANY, 'TbDespesasCarros', 'carro'),
			'tbSeguroses' => array(self::HAS_MANY, 'TbSeguros', 'carro'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_carro' => Yii::t('app', 'Id Carro'),
			'matricula' => Yii::t('app', 'Matricula'),
			'marca' => Yii::t('app', 'Marca'),
			'modelo' => Yii::t('app', 'Modelo'),
			'km_iniciais' => Yii::t('app', 'Km Iniciais'),
			'data_matricula' => Yii::t('app', 'Data Matricula'),
			'seguro' => null,
			'combust_inicial' => Yii::t('app', 'Combust Inicial'),
			'seguro0' => null,
			'tbDespesasCarroses' => null,
			'tbSeguroses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_carro', $this->id_carro);
		$criteria->compare('matricula', $this->matricula, true);
		$criteria->compare('marca', $this->marca, true);
		$criteria->compare('modelo', $this->modelo, true);
		$criteria->compare('km_iniciais', $this->km_iniciais);
		$criteria->compare('data_matricula', $this->data_matricula, true);
		$criteria->compare('seguro', $this->seguro);
		$criteria->compare('combust_inicial', $this->combust_inicial);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}