<?php

/**
 * This is the model base class for the table "tb_despesas_carros".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbDespesasCarros".
 *
 * Columns in table "tb_despesas_carros" available as properties of the model,
 * followed by relations of table "tb_despesas_carros" available as properties of the model.
 *
 * @property integer $id_despesa_carro
 * @property string $descricao
 * @property integer $tipo_desp
 * @property integer $movimento
 * @property string $data
 * @property integer $kms
 * @property integer $carro
 * @property integer $lt_combust
 * @property double $preco_lt
 * @property integer $user
 *
 * @property TbTipoDesp $tipoDesp
 * @property TbMovimentos $movimento0
 * @property TbCarros $carro0
 * @property TbUsers $user0
 */
abstract class BaseTbDespesasCarros extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tb_despesas_carros';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Despesa Carro |Despesas Carros', $n);
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('tipo_desp, movimento, kms, carro, lt_combust, user', 'numerical', 'integerOnly'=>true),
			array('preco_lt', 'numerical'),
			array('descricao', 'length', 'max'=>255),
			array('data', 'safe'),
			array('descricao, tipo_desp, movimento, data, kms, carro, lt_combust, preco_lt, user', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_despesa_carro, descricao, tipo_desp, movimento, data, kms, carro, lt_combust, preco_lt, user', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tipoDesp' => array(self::BELONGS_TO, 'TbTipoDesp', 'tipo_desp'),
			'movimento0' => array(self::BELONGS_TO, 'TbMovimentos', 'movimento'),
			'carro0' => array(self::BELONGS_TO, 'TbCarros', 'carro'),
			'user0' => array(self::BELONGS_TO, 'TbUsers', 'user'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_despesa_carro' => Yii::t('app', 'Id Despesa Carro'),
			'descricao' => Yii::t('app', 'Descricao'),
			'tipo_desp' => null,
			'movimento' => null,
			'data' => Yii::t('app', 'Data'),
			'kms' => Yii::t('app', 'Kms'),
			'carro' => null,
			'lt_combust' => Yii::t('app', 'Lt Combust'),
			'preco_lt' => Yii::t('app', 'Preco Lt'),
			'user' => null,
			'tipoDesp' => null,
			'movimento0' => null,
			'carro0' => null,
			'user0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_despesa_carro', $this->id_despesa_carro);
		$criteria->compare('descricao', $this->descricao, true);
		$criteria->compare('tipo_desp', $this->tipo_desp);
		$criteria->compare('movimento', $this->movimento);
		$criteria->compare('data', $this->data, true);
		$criteria->compare('kms', $this->kms);
		$criteria->compare('carro', $this->carro);
		$criteria->compare('lt_combust', $this->lt_combust);
		$criteria->compare('preco_lt', $this->preco_lt);
		$criteria->compare('user', $this->user);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}