<?php

/**
 * This is the model base class for the table "tb_bancos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbBancos".
 *
 * Columns in table "tb_bancos" available as properties of the model,
 * followed by relations of table "tb_bancos" available as properties of the model.
 *
 * @property integer $id_banco
 * @property string $nome
 * @property string $inicio_nib
 *
 * @property TbContas[] $tbContases
 */
abstract class BaseTbBancos extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tb_bancos';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Banco|Bancos', $n);
	}

	public static function representingColumn() {
		return 'nome';
	}

	public function rules() {
		return array(
			array('nome', 'length', 'max'=>255),
			array('inicio_nib', 'length', 'max'=>45),
			array('nome, inicio_nib', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_banco, nome, inicio_nib', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tbContases' => array(self::HAS_MANY, 'TbContas', 'banco'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_banco' => Yii::t('app', 'Id Banco'),
			'nome' => Yii::t('app', 'Nome'),
			'inicio_nib' => Yii::t('app', 'Inicio Nib'),
			'tbContases' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_banco', $this->id_banco);
		$criteria->compare('nome', $this->nome, true);
		$criteria->compare('inicio_nib', $this->inicio_nib, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}