<?php

/**
 * This is the model base class for the table "tb_seguros".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbSeguros".
 *
 * Columns in table "tb_seguros" available as properties of the model,
 * followed by relations of table "tb_seguros" available as properties of the model.
 *
 * @property integer $id_seguro
 * @property integer $user
 * @property integer $carro
 * @property string $num_seguro
 * @property string $data_inicio
 * @property string $data_fim
 * @property string $valor
 * @property integer $repeticao
 *
 * @property TbCarros[] $tbCarroses
 * @property TbUsers $user0
 * @property TbCarros $carro0
 * @property TbRepeticao $repeticao0
 */
abstract class BaseTbSeguros extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tb_seguros';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Seguro|Seguros', $n);
	}

	public static function representingColumn() {
		return 'num_seguro';
	}

	public function rules() {
		return array(
			array('user, carro, repeticao', 'numerical', 'integerOnly'=>true),
			array('num_seguro, valor', 'length', 'max'=>45),
			array('data_inicio, data_fim', 'safe'),
			array('user, carro, num_seguro, data_inicio, data_fim, valor, repeticao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_seguro, user, carro, num_seguro, data_inicio, data_fim, valor, repeticao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tbCarroses' => array(self::HAS_MANY, 'TbCarros', 'seguro'),
			'user0' => array(self::BELONGS_TO, 'TbUsers', 'user'),
			'carro0' => array(self::BELONGS_TO, 'TbCarros', 'carro'),
			'repeticao0' => array(self::BELONGS_TO, 'TbRepeticao', 'repeticao'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_seguro' => Yii::t('app', 'Id Seguro'),
			'user' => null,
			'carro' => null,
			'num_seguro' => Yii::t('app', 'Num Seguro'),
			'data_inicio' => Yii::t('app', 'Data Inicio'),
			'data_fim' => Yii::t('app', 'Data Fim'),
			'valor' => Yii::t('app', 'Valor'),
			'repeticao' => null,
			'tbCarroses' => null,
			'user0' => null,
			'carro0' => null,
			'repeticao0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_seguro', $this->id_seguro);
		$criteria->compare('user', $this->user);
		$criteria->compare('carro', $this->carro);
		$criteria->compare('num_seguro', $this->num_seguro, true);
		$criteria->compare('data_inicio', $this->data_inicio, true);
		$criteria->compare('data_fim', $this->data_fim, true);
		$criteria->compare('valor', $this->valor, true);
		$criteria->compare('repeticao', $this->repeticao);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}