<?php

/**
 * This is the model base class for the table "tb_tipo_desp".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbTipoDesp".
 *
 * Columns in table "tb_tipo_desp" available as properties of the model,
 * followed by relations of table "tb_tipo_desp" available as properties of the model.
 *
 * @property integer $id_tipo_desp
 * @property string $descricao
 *
 * @property TbDespesasCarros[] $tbDespesasCarroses
 * @property TbMovimentos[] $tbMovimentoses
 */
abstract class BaseTbTipoDesp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tb_tipo_desp';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tipo Despesa|Tipos Despesas', $n);
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('descricao', 'length', 'max'=>255),
			array('descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tipo_desp, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tbDespesasCarroses' => array(self::HAS_MANY, 'TbDespesasCarros', 'tipo_desp'),
			'tbMovimentoses' => array(self::HAS_MANY, 'TbMovimentos', 'tipo_desp'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tipo_desp' => Yii::t('app', 'Id Tipo Desp'),
			'descricao' => Yii::t('app', 'Descricao'),
			'tbDespesasCarroses' => null,
			'tbMovimentoses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tipo_desp', $this->id_tipo_desp);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}