<?php

/**
 * This is the model base class for the table "tb_repeticao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TbRepeticao".
 *
 * Columns in table "tb_repeticao" available as properties of the model,
 * followed by relations of table "tb_repeticao" available as properties of the model.
 *
 * @property integer $id_repeticao
 * @property string $descricao
 *
 * @property TbAgendaMov[] $tbAgendaMovs
 * @property TbSeguros[] $tbSeguroses
 */
abstract class BaseTbRepeticao extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tb_repeticao';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Repeticao|Repeticoes', $n);
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('descricao', 'length', 'max'=>45),
			array('descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_repeticao, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tbAgendaMovs' => array(self::HAS_MANY, 'TbAgendaMov', 'repeticao'),
			'tbSeguroses' => array(self::HAS_MANY, 'TbSeguros', 'repeticao'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_repeticao' => Yii::t('app', 'Id Repeticao'),
			'descricao' => Yii::t('app', 'Descricao'),
			'tbAgendaMovs' => null,
			'tbSeguroses' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_repeticao', $this->id_repeticao);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}